### ISSUE TITLE
Problème d'installation

### ISSUE THREAD

**Issue by andreaspastor** [nquinquenel/hashcode-2021#1]
Bonjour,

Je n'arrive pas à installer Java pour pouvoir utiliser votre code.
Quelle version faut-il?

Bonne journée à vous

**Comment by nquinquenel** [comment]
Bonjour très cher Andréas PASTOR, la version 11 de Java est suffisante pour faire tourner notre solution :)

**Comment by andreaspastor** [comment]
merci de votre rapide retour :)
